### ISSUE TITLE
Resolve GitLab Target Namespace From `.gitlab-ci.yml` Variable

### ISSUE THREAD

**Issue by tgmachina** [LLNL/hubcast#23]
## Problem/Opportunity Statement
When setting up Hubcast to mirror a repository, we can establish which source GitHub repository to use via app install, but need a way to determine the target namespace in GitLab to push the repository to.

This proposal is to leverage the `.gitlab-ci.yml` file that is already part of the repository and specify the target namespace in a key-value pair e.g.:

```yaml
variables:
  HUBCAST_NAMESPACE: "foo"
```

## What would success / a fix look like?

- [ ] Determine a key-value pair unused by GitLab to store namespace info
- [ ] Namespace info is derived and stored from `.gitlab-ci.yml` on the `main` branch only
- [ ] Namespace info is updated on changes to `.gitlab-ci.yml` when merged to `main` only
- [ ] User-facing documentation created specifying the key-value pair to set in `.gitlab-ci.yml`

**Comment by tgmachina** [comment]
fyi, @alecbcs

**Comment by alecbcs** [comment]
Looks great! Thanks for creating an issue to track this @tgmachina.
